services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  user-api:
    build:
      context: .
      dockerfile: ./src/UserApi/Dockerfile
    ports:
      - "5001:8080"

  order-api:
    build:
      context: .
      dockerfile: ./src/OrderApi/Dockerfile
    ports:
      - "5002:8080"
